import React, { useState, useEffect } from 'react';

import { Loader, Card, FormField } from '../components';

type PostType = {
  _id: string;
  // Add other properties as needed
}

type RenderCards = {
  data: PostType[] ; 
  title: string; 
}

// here is a reusable image Card to render images
// this will render the images if have any or resder the message in title 
const RenderCards: React.FC<RenderCards> = ({data, title}) => {
  if(data?.length > 0){
    return data.map((post) => <Card key={post._id} {...post}/>);
  } 
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
      {title}
    </h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');

  return (
    <section>
      {/* Title */}
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      {/* Input form */}
      <div className="mt-16">
        <FormField />
      </div>

      {/* it will be loading until fetching the pictures */}
      {/* also load until search reasult shows */}
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
          {/* Search result text */}
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for{' '}
                <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}

            {/* The grid of images */}

            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title='No search reasults found' />
              ) : (
                <RenderCards data={[]} title='No post found'/>
              )}
            </div>
          </>
        )}
      </div>

    </section>
  );
};

export default Home;
